CREATE TABLE IF NOT EXISTS `Users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(60) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`email`),
    UNIQUE (`username`)
);
CREATE DATABASE pawfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER 'pawfolio'@'localhost' IDENTIFIED BY 'changeme';
GRANT ALL PRIVILEGES ON pawfolio.* TO 'pawfolio'@'localhost';
FLUSH PRIVILEGES;
